security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            oauth:
                resource_owners:
                    pikabot_custom: "/login/check-custom"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                oauth_user_provider:
                    service: hwi_oauth.user.provider
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }